before_install:
 - openssl aes-256-cbc -K $encrypted_b8624f4f5df6_key -iv $encrypted_b8624f4f5df6_iv
  -in id_rsa.enc -out id_rsa -d
# 使用的语言
language: node_js

# 使用的nodejs版本
node_js:
 - 6.10.2

# 仓库的分支
branches:
  only:
  - master

# 改变文件权限
 - chmod 600 ~/.ssh/id_rsa

# 配置 ssh
 - eval $(ssh-agent)
 - ssh-add ~/.ssh/id_rsa
 - cp .travis/ssh_config ~/.ssh/config

# 配置git 的个人信息
 - git config --global user.name 'zhangzhw'
 - git config --global user.email zhangzhiwei_94@163.com

# 执行install
install:
 - npm install hexo-cli -g
 - npm install

# 执行命令脚本
script:
 - hexo clean
 - hexo g -d
