
language: node_js

node_js:
 - 6.10.2

branches:
  only:
  - master
  
before_install:
 - openssl aes-256-cbc -K $encrypted_b8624f4f5df6_key -iv $encrypted_b8624f4f5df6_iv -in id_rsa.enc -out id_rsa -d

 - chmod 600 ~/.ssh/id_rsa

 - eval $(ssh-agent)
 - ssh-add ~/.ssh/id_rsa
 - cp .travis/ssh_config ~/.ssh/config

 - git config --global user.name 'zhangzhw'
 - git config --global user.email zhangzhiwei_94@163.com

install:
 - npm install hexo-cli -g
 - npm install

script:
 - hexo clean
 - hexo g -d

