
language: node_js

node_js:
 - 6.10.2

branches:
  only:
  - master
  
before_install:
 - openssl aes-256-cbc -K $encrypted_b8624f4f5df6_key -iv $encrypted_b8624f4f5df6_iv -in id_rsa.enc -out id_rsa -d
 - cd ~
 - ls -al
 - ls .travis -al
 - ls .ssh -al
 - ls build/zhangzhw -al
 - ls builds -al
 - chmod 600 ~/build/zhangzhw/php_post_and_receive/ssh/id_rsa

 - eval $(ssh-agent)
 - ssh-add ~/build/zhangzhw/php_post_and_receive/ssh/id_rsa
 - cp ~/build/zhangzhw/php_post_and_receive/.travis/ssh_config ~/.ssh/config

 - git config --global user.name 'zhangzhw'
 - git config --global user.email zhangzhiwei_94@163.com

install:
 - npm install hexo-cli -g
 - npm install

script:
 - hexo clean
 - hexo g -d

